name:  behaviors
description: >
    Behaviors are a way to attach new functionality to DOM elements which match
    certain CSS selectors.
version: 0.1.0-dev
author: Justin Fagnani <justinfagnani@google.com>
homepage: https://github.com/justinfagnani/behaviors.dart
dev_dependencies:
  active_query: any
  browser: any
  polymer: '>= 0.10.0-pre.9'
  unittest: '>= 0.10.0 < 0.11.0'
